### ISSUE TITLE
Difference between total ELO in ranking table and statistics graph

### ISSUE THREAD

**Issue by shinoceros** [shinoceros/kickermanager#38]
The total ELO in ranking table differs from last value in statistics graph.
Check both DB queries!

**Comment by Campus77** [comment]
Hi, the problem is the datetime format conversion. If you execute `"SELECT COUNT(*) FROM matches WHERE season = 6"`, the result will differ from `"SELECT COUNT(*) FROM matches WHERE DATE(timestamp) >= '2014-10-20 12:11:13' AND DATE(timestamp) <= '2016-02-12 13:49:34'`, even though the timestamps from the second statement represent the start and end of the sixth season.

The statement `SELECT COUNT(*) FROM matches WHERE (DATE(timestamp) >= STR_TO_DATE('2014-10-20 12:11:13', '%Y-%m-%d') AND DATE(timestamp) <= STR_TO_DATE('2016-02-12 13:49:34', '%Y-%m-%d'))` will return the correct number of matches.

The statement `SELECT COUNT(*) FROM matches WHERE timestamp >= '2014-10-20 12:11:13' AND timestamp <= '2016-02-12 13:49:34'` will also return the correct result.

So the it depends on the data format of the parameters `$from` and `$to` of function `GetStatsForRange($from, $to)` which SELECT statement is suitable.
